server:
  port: 27149
  uri-encoding: UTF-8
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: LEGACYHTML5
  mvc:
    static-path-pattern: /static/**